"use strict";

/* eslint-disable @typescript-eslint/no-unused-vars */

var systemDictionary = {
  "Basic settings": {
    en: "Basic settings",
    de: "Grundeinstellungen",
    ru: "Основные настройки",
    pt: "Configurações básicas",
    nl: "Basisinstellingen",
    fr: "Paramètres de base",
    it: "Impostazioni di base",
    es: "Ajustes básicos",
    pl: "Ustawienia podstawowe",
    uk: "Основні налаштування",
    "zh-cn": "基本设置",
  },
  "Advanced settings": {
    en: "Advanced settings",
    de: "Erweiterte Einstellungen",
    ru: "Расширенные настройки",
    pt: "Configurações avançadas",
    nl: "Geavanceerde instellingen",
    fr: "Paramètres avancés",
    it: "Impostazioni avanzate",
    es: "Ajustes avanzados",
    pl: "Ustawienia zaawansowane",
    uk: "Розширені налаштування",
    "zh-cn": "高级设置",
  },
  "Inverter IP": {
    en: "Inverter IP",
    de: "Wechselrichter-IP",
    ru: "IP инвертора",
    pt: "IP do inversor",
    nl: "Omvormer-IP",
    fr: "IP de l'onduleur",
    it: "IP inverter",
    es: "IP del inversor",
    pl: "IP falownika",
    uk: "IP інвертора",
    "zh-cn": "逆变器 IP",
  },
  "Only the IPv4 address is saved here.": {
    en: "Only the IPv4 address is saved here.",
    de: "Hier wird nur die IPv4-Adresse gespeichert.",
    ru: "Здесь сохраняется только IPv4-адрес.",
    pt: "Somente o endereço IPv4 é salvo aqui.",
    nl: "Alleen het IPv4-adres wordt hier opgeslagen.",
    fr: "Seule l'adresse IPv4 est enregistrée ici.",
    it: "Qui viene salvato solo l'indirizzo IPv4.",
    es: "Aquí solo se guarda la dirección IPv4.",
    pl: "Tutaj zapisywany jest tylko adres IPv4.",
    uk: "Тут зберігається лише IPv4-адреса.",
    "zh-cn": "此处只保存 IPv4 地址。",
  },
  "Validate inverter IP": {
    en: "Validate inverter IP",
    de: "Wechselrichter-IP prüfen",
    ru: "Проверить IP инвертора",
    pt: "Validar IP do inversor",
    nl: "Omvormer-IP controleren",
    fr: "Valider l'IP de l'onduleur",
    it: "Verifica IP inverter",
    es: "Validar IP del inversor",
    pl: "Sprawdź IP falownika",
    uk: "Перевірити IP інвертора",
    "zh-cn": "验证逆变器 IP",
  },
  "Discovery subnet": {
    en: "Discovery subnet",
    de: "Such-Subnetz",
    ru: "Подсеть поиска",
    pt: "Sub-rede de descoberta",
    nl: "Zoeksubnet",
    fr: "Sous-réseau de découverte",
    it: "Subnet di ricerca",
    es: "Subred de descubrimiento",
    pl: "Podsieć wyszukiwania",
    uk: "Підмережа пошуку",
    "zh-cn": "发现子网",
  },
  "Optional /24 subnet. Empty uses configured IP and local interfaces.": {
    en: "Optional /24 subnet. Empty uses configured IP and local interfaces.",
    de: "Optionales /24-Subnetz. Leer nutzt konfigurierte IP und lokale Schnittstellen.",
    ru: "Необязательная подсеть /24. Пусто: используются настроенный IP и локальные интерфейсы.",
    pt: "Sub-rede /24 opcional. Vazio usa o IP configurado e interfaces locais.",
    nl: "Optioneel /24-subnet. Leeg gebruikt geconfigureerd IP en lokale interfaces.",
    fr: "Sous-réseau /24 optionnel. Vide utilise l'IP configurée et les interfaces locales.",
    it: "Subnet /24 opzionale. Vuoto usa l'IP configurato e le interfacce locali.",
    es: "Subred /24 opcional. Vacío usa la IP configurada y las interfaces locales.",
    pl: "Opcjonalna podsieć /24. Puste używa skonfigurowanego IP i lokalnych interfejsów.",
    uk: "Необов'язкова підмережа /24. Порожнє поле використовує налаштований IP і локальні інтерфейси.",
    "zh-cn": "可选 /24 子网。留空则使用已配置 IP 和本地接口。",
  },
  "Discover inverters": {
    en: "Discover inverters",
    de: "Wechselrichter suchen",
    ru: "Найти инверторы",
    pt: "Descobrir inversores",
    nl: "Omvormers zoeken",
    fr: "Découvrir les onduleurs",
    it: "Cerca inverter",
    es: "Descubrir inversores",
    pl: "Wyszukaj falowniki",
    uk: "Знайти інвертори",
    "zh-cn": "发现逆变器",
  },
  "Poll cycle": {
    en: "Poll cycle",
    de: "Abfragezyklus",
    ru: "Цикл опроса",
    pt: "Ciclo de consulta",
    nl: "Pollcyclus",
    fr: "Cycle d'interrogation",
    it: "Ciclo di polling",
    es: "Ciclo de sondeo",
    pl: "Cykl odpytywania",
    uk: "Цикл опитування",
    "zh-cn": "轮询周期",
  },
  "Seconds, 10-3600": {
    en: "Seconds, 10-3600",
    de: "Sekunden, 10-3600",
    ru: "Секунды, 10-3600",
    pt: "Segundos, 10-3600",
    nl: "Seconden, 10-3600",
    fr: "Secondes, 10-3600",
    it: "Secondi, 10-3600",
    es: "Segundos, 10-3600",
    pl: "Sekundy, 10-3600",
    uk: "Секунди, 10-3600",
    "zh-cn": "秒，10-3600",
  },
  Timeout: {
    en: "Timeout",
    de: "Zeitlimit",
    ru: "Тайм-аут",
    pt: "Tempo limite",
    nl: "Time-out",
    fr: "Délai d'attente",
    it: "Timeout",
    es: "Tiempo de espera",
    pl: "Limit czasu",
    uk: "Тайм-аут",
    "zh-cn": "超时",
  },
  "Milliseconds, 1000-30000": {
    en: "Milliseconds, 1000-30000",
    de: "Millisekunden, 1000-30000",
    ru: "Миллисекунды, 1000-30000",
    pt: "Milissegundos, 1000-30000",
    nl: "Milliseconden, 1000-30000",
    fr: "Millisecondes, 1000-30000",
    it: "Millisecondi, 1000-30000",
    es: "Milisegundos, 1000-30000",
    pl: "Milisekundy, 1000-30000",
    uk: "Мілісекунди, 1000-30000",
    "zh-cn": "毫秒，1000-30000",
  },
  Retries: {
    en: "Retries",
    de: "Wiederholungen",
    ru: "Повторы",
    pt: "Tentativas",
    nl: "Nieuwe pogingen",
    fr: "Tentatives",
    it: "Tentativi",
    es: "Reintentos",
    pl: "Ponowienia",
    uk: "Повторні спроби",
    "zh-cn": "重试次数",
  },
  "0-5 per UDP request": {
    en: "0-5 per UDP request",
    de: "0-5 pro UDP-Anfrage",
    ru: "0-5 на UDP-запрос",
    pt: "0-5 por requisição UDP",
    nl: "0-5 per UDP-verzoek",
    fr: "0-5 par requête UDP",
    it: "0-5 per richiesta UDP",
    es: "0-5 por solicitud UDP",
    pl: "0-5 na żądanie UDP",
    uk: "0-5 на UDP-запит",
    "zh-cn": "每个 UDP 请求 0-5 次",
  },
  "Poll extended registers": {
    en: "Poll extended registers",
    de: "Erweiterte Register abfragen",
    ru: "Опрос расширенных регистров",
    pt: "Consultar registradores estendidos",
    nl: "Uitgebreide registers pollen",
    fr: "Interroger les registres étendus",
    it: "Interroga registri estesi",
    es: "Sondear registros extendidos",
    pl: "Odpytuj rozszerzone rejestry",
    uk: "Опитувати розширені регістри",
    "zh-cn": "轮询扩展寄存器",
  },
  "Poll SIMCCID": {
    en: "Poll SIMCCID",
    de: "SIMCCID abfragen",
    ru: "Опрос SIMCCID",
    pt: "Consultar SIMCCID",
    nl: "SIMCCID pollen",
    fr: "Interroger le SIMCCID",
    it: "Interroga SIMCCID",
    es: "Sondear SIMCCID",
    pl: "Odpytuj SIMCCID",
    uk: "Опитувати SIMCCID",
    "zh-cn": "轮询 SIMCCID",
  },
  "Poll extended meter": {
    en: "Poll extended meter",
    de: "Erweiterten Zähler abfragen",
    ru: "Опрос расширенного счетчика",
    pt: "Consultar medidor estendido",
    nl: "Uitgebreide meter pollen",
    fr: "Interroger le compteur étendu",
    it: "Interroga contatore esteso",
    es: "Sondear medidor extendido",
    pl: "Odpytuj rozszerzony licznik",
    uk: "Опитувати розширений лічильник",
    "zh-cn": "轮询扩展电表",
  },
  "Poll flash info": {
    en: "Poll flash info",
    de: "Flash-Info abfragen",
    ru: "Опрос flash-информации",
    pt: "Consultar informações flash",
    nl: "Flashinfo pollen",
    fr: "Interroger les infos flash",
    it: "Interroga info flash",
    es: "Sondear información flash",
    pl: "Odpytuj informacje flash",
    uk: "Опитувати flash-інформацію",
    "zh-cn": "轮询 Flash 信息",
  },
  "Poll BMS extended": {
    en: "Poll BMS extended",
    de: "Erweiterte BMS-Daten abfragen",
    ru: "Опрос расширенных данных BMS",
    pt: "Consultar BMS estendido",
    nl: "Uitgebreide BMS-gegevens pollen",
    fr: "Interroger les données BMS étendues",
    it: "Interroga BMS esteso",
    es: "Sondear BMS extendido",
    pl: "Odpytuj rozszerzone BMS",
    uk: "Опитувати розширені дані BMS",
    "zh-cn": "轮询扩展 BMS",
  },
  "Poll BMS detail": {
    en: "Poll BMS detail",
    de: "BMS-Details abfragen",
    ru: "Опрос деталей BMS",
    pt: "Consultar detalhes do BMS",
    nl: "BMS-details pollen",
    fr: "Interroger les détails BMS",
    it: "Interroga dettagli BMS",
    es: "Sondear detalles BMS",
    pl: "Odpytuj szczegóły BMS",
    uk: "Опитувати деталі BMS",
    "zh-cn": "轮询 BMS 详情",
  },
  "Poll CEI auto test": {
    en: "Poll CEI auto test",
    de: "CEI-Autotest abfragen",
    ru: "Опрос автотеста CEI",
    pt: "Consultar autoteste CEI",
    nl: "CEI-autotest pollen",
    fr: "Interroger l'auto-test CEI",
    it: "Interroga autotest CEI",
    es: "Sondear prueba automática CEI",
    pl: "Odpytuj autotest CEI",
    uk: "Опитувати автотест CEI",
    "zh-cn": "轮询 CEI 自动测试",
  },
  "Poll power limit": {
    en: "Poll power limit",
    de: "Leistungsbegrenzung abfragen",
    ru: "Опрос ограничения мощности",
    pt: "Consultar limite de potência",
    nl: "Vermogenslimiet pollen",
    fr: "Interroger la limite de puissance",
    it: "Interroga limite di potenza",
    es: "Sondear límite de potencia",
    pl: "Odpytuj limit mocy",
    uk: "Опитувати обмеження потужності",
    "zh-cn": "轮询功率限制",
  },
  "Inverter reachable": {
    en: "Inverter reachable",
    de: "Wechselrichter erreichbar",
    ru: "Инвертор доступен",
    pt: "Inversor acessível",
    nl: "Omvormer bereikbaar",
    fr: "Onduleur joignable",
    it: "Inverter raggiungibile",
    es: "Inversor accesible",
    pl: "Falownik dostępny",
    uk: "Інвертор доступний",
    "zh-cn": "逆变器可访问",
  },
  "Inverter not reachable": {
    en: "Inverter not reachable",
    de: "Wechselrichter nicht erreichbar",
    ru: "Инвертор недоступен",
    pt: "Inversor inacessível",
    nl: "Omvormer niet bereikbaar",
    fr: "Onduleur non joignable",
    it: "Inverter non raggiungibile",
    es: "Inversor no accesible",
    pl: "Falownik niedostępny",
    uk: "Інвертор недоступний",
    "zh-cn": "逆变器不可访问",
  },
  "IP %s applied": {
    en: "IP %s applied",
    de: "IP %s übernommen",
    ru: "IP %s применен",
    pt: "IP %s aplicado",
    nl: "IP %s toegepast",
    fr: "IP %s appliquée",
    it: "IP %s applicato",
    es: "IP %s aplicada",
    pl: "IP %s zastosowany",
    uk: "IP %s застосовано",
    "zh-cn": "已应用 IP %s",
  },
  "No inverter found. Searched %s addresses.": {
    en: "No inverter found. Searched %s addresses.",
    de: "Kein Wechselrichter gefunden. %s Adressen durchsucht.",
    ru: "Инвертор не найден. Проверено адресов: %s.",
    pt: "Nenhum inversor encontrado. %s endereços pesquisados.",
    nl: "Geen omvormer gevonden. %s adressen doorzocht.",
    fr: "Aucun onduleur trouvé. %s adresses recherchées.",
    it: "Nessun inverter trovato. Cercati %s indirizzi.",
    es: "No se encontró ningún inversor. Se buscaron %s direcciones.",
    pl: "Nie znaleziono falownika. Przeszukano %s adresów.",
    uk: "Інвертор не знайдено. Перевірено адрес: %s.",
    "zh-cn": "未找到逆变器。已搜索 %s 个地址。",
  },
  "Found %s inverter(s). Searched %s addresses.": {
    en: "Found %s inverter(s). Searched %s addresses.",
    de: "%s Wechselrichter gefunden. %s Adressen durchsucht.",
    ru: "Найдено инверторов: %s. Проверено адресов: %s.",
    pt: "%s inversor(es) encontrado(s). %s endereços pesquisados.",
    nl: "%s omvormer(s) gevonden. %s adressen doorzocht.",
    fr: "%s onduleur(s) trouvé(s). %s adresses recherchées.",
    it: "Trovati %s inverter. Cercati %s indirizzi.",
    es: "Se encontraron %s inversor(es). Se buscaron %s direcciones.",
    pl: "Znaleziono falowników: %s. Przeszukano adresów: %s.",
    uk: "Знайдено інверторів: %s. Перевірено адрес: %s.",
    "zh-cn": "找到 %s 个逆变器。已搜索 %s 个地址。",
  },
  Use: {
    en: "Use",
    de: "Verwenden",
    ru: "Использовать",
    pt: "Usar",
    nl: "Gebruiken",
    fr: "Utiliser",
    it: "Usa",
    es: "Usar",
    pl: "Użyj",
    uk: "Використати",
    "zh-cn": "使用",
  },
};
